-- Postgres baseline (ADR-0015, docs/core/postgres-port-audit.md). Consolidates the end state of the SQLite
-- migrations 001..020 in ../migrations; the SQLite store stays as a standby and is not changed by this file.
--
-- Differences from the SQLite schema, all deliberate:
--   * every tenant table carries household_id, tied to its parent by a composite foreign key, so a row can never
--     point at a parent in another household and row-level security stays a one-column policy;
--   * `seq` (identity) replaces SQLite's implicit rowid wherever the code orders by rowid;
--   * COLLATE NOCASE becomes a lower() index; triggers are PL/pgSQL; REAL is DOUBLE PRECISION;
--   * planner_skips is keyed by household_id too.
-- Dates stay ISO TEXT and flags stay INTEGER 0/1 so API output does not change.

CREATE TABLE households (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL CHECK (length(trim(name)) > 0),
    timezone TEXT NOT NULL,
    country_code TEXT,
    region TEXT,
    owner_member_id TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    modules_configured INTEGER NOT NULL DEFAULT 0 CHECK (modules_configured IN (0, 1)),
    latitude DOUBLE PRECISION CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    longitude DOUBLE PRECISION CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    household_type TEXT NOT NULL DEFAULT 'family'
);

CREATE TABLE household_members (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('adult', 'child', 'helper')),
    name TEXT NOT NULL CHECK (length(trim(name)) > 0),
    birth_date TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    modules_restricted INTEGER NOT NULL DEFAULT 0 CHECK (modules_restricted IN (0, 1)),
    avatar TEXT,
    color TEXT,
    UNIQUE (id, household_id)
);
CREATE INDEX household_members_by_household ON household_members(household_id, role, name);

-- The owner must belong to the household; checked at commit so a household and its first member can be inserted together.
ALTER TABLE households ADD FOREIGN KEY (owner_member_id, id)
    REFERENCES household_members(id, household_id) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE household_modules (
    household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    module_id TEXT NOT NULL CHECK (length(module_id) > 0),
    PRIMARY KEY (household_id, module_id)
);

CREATE TABLE member_modules (
    household_id TEXT NOT NULL,
    member_id TEXT NOT NULL,
    module_id TEXT NOT NULL CHECK (length(module_id) > 0),
    PRIMARY KEY (member_id, module_id),
    FOREIGN KEY (member_id, household_id) REFERENCES household_members(id, household_id) ON DELETE CASCADE
);

-- Adults and children -----------------------------------------------------------------------------------------

CREATE TABLE adult_settings (
    member_id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL,
    work_start TEXT,
    work_end TEXT,
    commute_minutes INTEGER CHECK (commute_minutes IS NULL OR commute_minutes >= 0),
    evening_weekend_availability TEXT NOT NULL DEFAULT 'not_set'
        CHECK (evening_weekend_availability IN ('not_set', 'available', 'unavailable', 'varies')),
    focus_start TEXT,
    focus_end TEXT,
    babysitting_max_evenings INTEGER
        CHECK (babysitting_max_evenings IS NULL OR babysitting_max_evenings >= 0),
    babysitting_notice TEXT NOT NULL DEFAULT 'not_set'
        CHECK (babysitting_notice IN ('not_set', 'same_day', 'one_day', 'two_days', 'one_week')),
    UNIQUE (member_id, household_id),
    FOREIGN KEY (member_id, household_id) REFERENCES household_members(id, household_id) ON DELETE CASCADE
);

CREATE TABLE adult_work_days (
    member_id TEXT NOT NULL,
    household_id TEXT NOT NULL,
    weekday INTEGER NOT NULL CHECK (weekday BETWEEN 0 AND 6),
    location TEXT NOT NULL CHECK (location IN ('office', 'home', 'off')),
    PRIMARY KEY (member_id, weekday),
    FOREIGN KEY (member_id, household_id) REFERENCES adult_settings(member_id, household_id) ON DELETE CASCADE
);

CREATE TABLE child_settings (
    member_id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL,
    school_or_care_name TEXT,
    school_type_or_year TEXT,
    after_school_care TEXT NOT NULL DEFAULT 'not_set'
        CHECK (after_school_care IN ('not_set', 'yes', 'no', 'varies')),
    pickup_time TEXT,
    supervision_policy TEXT NOT NULL DEFAULT 'not_set'
        CHECK (supervision_policy IN ('not_set', 'always', 'sometimes', 'independent')),
    travel_minutes INTEGER CHECK (travel_minutes IS NULL OR travel_minutes >= 0),
    dropoff_time TEXT,
    commute_mode TEXT CHECK (commute_mode IS NULL OR commute_mode IN ('walk', 'cycle', 'car')),
    UNIQUE (member_id, household_id),
    FOREIGN KEY (member_id, household_id) REFERENCES household_members(id, household_id) ON DELETE CASCADE
);

CREATE TABLE child_care_days (
    member_id TEXT NOT NULL,
    household_id TEXT NOT NULL,
    weekday INTEGER NOT NULL CHECK (weekday BETWEEN 0 AND 6),
    PRIMARY KEY (member_id, weekday),
    FOREIGN KEY (member_id, household_id) REFERENCES child_settings(member_id, household_id) ON DELETE CASCADE
);

CREATE TABLE child_activities (
    id TEXT PRIMARY KEY,
    member_id TEXT NOT NULL,
    household_id TEXT NOT NULL,
    name TEXT NOT NULL CHECK (length(trim(name)) > 0),
    location TEXT,
    start_time TEXT,
    end_time TEXT,
    commute_mode TEXT CHECK (commute_mode IS NULL OR commute_mode IN ('walk', 'cycle', 'car')),
    travel_minutes INTEGER CHECK (travel_minutes IS NULL OR travel_minutes >= 0),
    escort TEXT NOT NULL DEFAULT 'independent' CHECK (escort IN ('independent', 'parent')),
    escort_adult_id TEXT,
    UNIQUE (id, household_id),
    FOREIGN KEY (member_id, household_id) REFERENCES child_settings(member_id, household_id) ON DELETE CASCADE
);

CREATE TABLE child_activity_days (
    activity_id TEXT NOT NULL,
    household_id TEXT NOT NULL,
    weekday INTEGER NOT NULL CHECK (weekday BETWEEN 0 AND 6),
    PRIMARY KEY (activity_id, weekday),
    FOREIGN KEY (activity_id, household_id) REFERENCES child_activities(id, household_id) ON DELETE CASCADE
);

CREATE TABLE child_pickup_adults (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    child_id TEXT NOT NULL,
    adult_id TEXT NOT NULL,
    household_id TEXT NOT NULL,
    PRIMARY KEY (child_id, adult_id),
    FOREIGN KEY (child_id, household_id) REFERENCES household_members(id, household_id) ON DELETE CASCADE,
    FOREIGN KEY (adult_id, household_id) REFERENCES household_members(id, household_id) ON DELETE CASCADE
);

CREATE TABLE child_dropoff_adults (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    child_id TEXT NOT NULL,
    adult_id TEXT NOT NULL,
    household_id TEXT NOT NULL,
    PRIMARY KEY (child_id, adult_id),
    FOREIGN KEY (child_id, household_id) REFERENCES household_members(id, household_id) ON DELETE CASCADE,
    FOREIGN KEY (adult_id, household_id) REFERENCES household_members(id, household_id) ON DELETE CASCADE
);

-- Calendars, generated chores, chore series, reminders -------------------------------------------------------------

CREATE TABLE calendar_sources (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    name TEXT NOT NULL CHECK (length(trim(name)) > 0),
    category TEXT NOT NULL CHECK (category IN (
        'waste_collection', 'school_care', 'sport_activity', 'work', 'family', 'other'
    )),
    subscription_url TEXT NOT NULL,
    access_mode TEXT NOT NULL DEFAULT 'read_only' CHECK (access_mode = 'read_only'),
    connection_state TEXT NOT NULL DEFAULT 'not_checked'
        CHECK (connection_state IN ('not_checked', 'available', 'unavailable', 'stale', 'unknown')),
    last_checked_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (id, household_id)
);

CREATE TABLE calendar_source_members (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source_id TEXT NOT NULL,
    household_id TEXT NOT NULL,
    member_id TEXT NOT NULL,
    PRIMARY KEY (source_id, member_id),
    FOREIGN KEY (source_id, household_id) REFERENCES calendar_sources(id, household_id) ON DELETE CASCADE,
    FOREIGN KEY (member_id, household_id) REFERENCES household_members(id, household_id) ON DELETE CASCADE
);

CREATE TABLE chore_generation_rules (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    source_id TEXT NOT NULL,
    title_template TEXT NOT NULL CHECK (length(trim(title_template)) > 0),
    enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (id, source_id),
    FOREIGN KEY (source_id, household_id) REFERENCES calendar_sources(id, household_id) ON DELETE CASCADE
);

CREATE TABLE chore_rule_assignees (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    rule_id TEXT NOT NULL,
    source_id TEXT NOT NULL,
    member_id TEXT NOT NULL,
    household_id TEXT NOT NULL,
    PRIMARY KEY (rule_id, member_id),
    FOREIGN KEY (rule_id, source_id) REFERENCES chore_generation_rules(id, source_id) ON DELETE CASCADE,
    FOREIGN KEY (source_id, household_id) REFERENCES calendar_sources(id, household_id) ON DELETE CASCADE,
    FOREIGN KEY (member_id, household_id) REFERENCES household_members(id, household_id) ON DELETE CASCADE
);

CREATE TABLE chores (
    id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    title TEXT NOT NULL CHECK (length(trim(title)) > 0),
    due_at TEXT,
    state TEXT NOT NULL DEFAULT 'open' CHECK (state IN ('open', 'completed', 'cancelled')),
    data_state TEXT NOT NULL CHECK (data_state IN ('measured', 'forecast', 'manual', 'unavailable', 'demo')),
    availability_status TEXT NOT NULL DEFAULT 'available'
        CHECK (availability_status IN ('available', 'unavailable', 'unknown')),
    availability_reason TEXT,
    source_observed_at TEXT,
    ingested_at TEXT NOT NULL,
    source_id TEXT,
    source_occurrence_ref TEXT,
    generation_rule_id TEXT,
    manually_modified INTEGER NOT NULL DEFAULT 0 CHECK (manually_modified IN (0, 1)),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CHECK (
        (source_id IS NULL AND source_occurrence_ref IS NULL AND generation_rule_id IS NULL)
        OR
        (source_id IS NOT NULL AND source_occurrence_ref IS NOT NULL AND generation_rule_id IS NOT NULL)
    ),
    UNIQUE (id, household_id),
    UNIQUE (source_id, source_occurrence_ref, generation_rule_id),
    FOREIGN KEY (source_id, household_id) REFERENCES calendar_sources(id, household_id) ON DELETE CASCADE,
    FOREIGN KEY (generation_rule_id, source_id) REFERENCES chore_generation_rules(id, source_id) ON DELETE CASCADE
);
CREATE INDEX chores_by_household_state_due ON chores(household_id, state, due_at);

CREATE TABLE chore_assignees (
    chore_id TEXT NOT NULL,
    member_id TEXT NOT NULL,
    household_id TEXT NOT NULL,
    PRIMARY KEY (chore_id, member_id),
    FOREIGN KEY (chore_id, household_id) REFERENCES chores(id, household_id) ON DELETE CASCADE,
    FOREIGN KEY (member_id, household_id) REFERENCES household_members(id, household_id) ON DELETE CASCADE
);

CREATE TABLE chore_series (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    title TEXT NOT NULL CHECK (length(trim(title)) > 0),
    assignee_id TEXT,
    weekdays TEXT NOT NULL DEFAULT '',
    due_time TEXT,
    archived INTEGER NOT NULL DEFAULT 0 CHECK (archived IN (0, 1)),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    day_part TEXT CHECK (day_part IS NULL OR day_part IN ('morning', 'day', 'evening')),
    UNIQUE (id, household_id),
    FOREIGN KEY (assignee_id, household_id) REFERENCES household_members(id, household_id) ON DELETE SET NULL (assignee_id)
);
CREATE INDEX chore_series_by_household ON chore_series(household_id, archived);

CREATE TABLE chore_completions (
    series_id TEXT NOT NULL,
    household_id TEXT NOT NULL,
    day TEXT NOT NULL,
    completed_by TEXT,
    completed_at TEXT NOT NULL,
    PRIMARY KEY (series_id, day),
    FOREIGN KEY (series_id, household_id) REFERENCES chore_series(id, household_id) ON DELETE CASCADE
);

CREATE TABLE reminders (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    title TEXT NOT NULL CHECK (length(trim(title)) > 0),
    member_id TEXT,
    on_date TEXT,
    weekdays TEXT NOT NULL DEFAULT '',
    day_part TEXT CHECK (day_part IS NULL OR day_part IN ('morning', 'day', 'evening')),
    archived INTEGER NOT NULL DEFAULT 0 CHECK (archived IN (0, 1)),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (id, household_id),
    FOREIGN KEY (member_id, household_id) REFERENCES household_members(id, household_id) ON DELETE SET NULL (member_id)
);
CREATE INDEX reminders_by_household ON reminders(household_id, archived, on_date);

CREATE TABLE reminder_states (
    household_id TEXT NOT NULL,
    reminder_id TEXT NOT NULL,
    member_id TEXT NOT NULL DEFAULT '',
    day TEXT NOT NULL,
    state TEXT NOT NULL CHECK (state IN ('done', 'na')),
    updated_at TEXT NOT NULL,
    PRIMARY KEY (reminder_id, member_id, day),
    FOREIGN KEY (reminder_id, household_id) REFERENCES reminders(id, household_id) ON DELETE CASCADE
);

CREATE TABLE planner_skips (
    household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    kind TEXT NOT NULL CHECK (kind IN ('chore', 'reminder')),
    item_id TEXT NOT NULL,
    day TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (household_id, kind, item_id, day)
);
CREATE INDEX planner_skips_by_day ON planner_skips(household_id, day);

-- Energy -------------------------------------------------------------------------------------------------------------

CREATE TABLE energy_connections (
    household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    provider TEXT NOT NULL CHECK (provider IN ('tibber', 'solaredge')),
    secret TEXT NOT NULL CHECK (length(secret) > 0),
    config TEXT NOT NULL DEFAULT '{}',
    updated_at TEXT NOT NULL,
    PRIMARY KEY (household_id, provider)
);

CREATE TABLE meter_readings (
    household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    meter TEXT NOT NULL CHECK (length(meter) > 0),
    read_on TEXT NOT NULL,
    value DOUBLE PRECISION NOT NULL CHECK (value >= 0),
    note TEXT NOT NULL DEFAULT '',
    updated_at TEXT NOT NULL,
    PRIMARY KEY (household_id, meter, read_on)
);

-- Kids ---------------------------------------------------------------------------------------------------------------

CREATE TABLE kid_settings (
    household_id TEXT PRIMARY KEY REFERENCES households(id) ON DELETE CASCADE,
    core_written_pct INTEGER NOT NULL DEFAULT 50 CHECK (core_written_pct BETWEEN 0 AND 100),
    minor_written_pct INTEGER NOT NULL DEFAULT 30 CHECK (minor_written_pct BETWEEN 0 AND 100),
    elective_written_pct INTEGER NOT NULL DEFAULT 30 CHECK (elective_written_pct BETWEEN 0 AND 100)
);

CREATE TABLE kid_star_chores (
    series_id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL,
    FOREIGN KEY (series_id, household_id) REFERENCES chore_series(id, household_id) ON DELETE CASCADE
);

CREATE TABLE kid_chore_outcomes (
    series_id TEXT NOT NULL,
    household_id TEXT NOT NULL,
    day TEXT NOT NULL,
    outcome TEXT NOT NULL CHECK (outcome IN ('well', 'again')),
    granted_at TEXT NOT NULL,
    PRIMARY KEY (series_id, day),
    FOREIGN KEY (series_id, household_id) REFERENCES chore_series(id, household_id) ON DELETE CASCADE
);

CREATE TABLE kid_goals (
    id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL,
    member_id TEXT NOT NULL,
    title TEXT NOT NULL CHECK (length(trim(title)) > 0),
    note TEXT,
    cost INTEGER NOT NULL CHECK (cost BETWEEN 1 AND 10000),
    started_on TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'approved', 'archived')),
    approved_at TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (member_id, household_id) REFERENCES household_members(id, household_id) ON DELETE CASCADE
);
CREATE INDEX kid_goals_by_member ON kid_goals(member_id, status);

CREATE TABLE kid_subjects (
    id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL,
    member_id TEXT NOT NULL,
    name TEXT NOT NULL CHECK (length(trim(name)) > 0),
    kind TEXT NOT NULL DEFAULT 'minor' CHECK (kind IN ('core', 'minor', 'elective')),
    -- archived: the lesson left the plan. Grades are kept and the subject returns if the lesson is added again.
    archived INTEGER NOT NULL DEFAULT 0 CHECK (archived IN (0, 1)),
    created_at TEXT NOT NULL,
    code TEXT,
    UNIQUE (id, household_id),
    FOREIGN KEY (member_id, household_id) REFERENCES household_members(id, household_id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX kid_subjects_by_name ON kid_subjects(member_id, lower(name));

CREATE TABLE kid_grades (
    id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL,
    subject_id TEXT NOT NULL,
    grade_type TEXT NOT NULL CHECK (grade_type IN ('written', 'oral')),
    grade DOUBLE PRECISION NOT NULL CHECK (grade BETWEEN 1 AND 6),
    given_on TEXT NOT NULL,
    note TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (subject_id, household_id) REFERENCES kid_subjects(id, household_id) ON DELETE CASCADE
);
CREATE INDEX kid_grades_by_subject ON kid_grades(subject_id, given_on);

CREATE TABLE kid_meds (
    id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL,
    member_id TEXT NOT NULL,
    name TEXT NOT NULL CHECK (length(trim(name)) > 0),
    dose TEXT,
    time_of_day TEXT NOT NULL,
    weekdays TEXT NOT NULL DEFAULT '',
    remind_member_id TEXT,
    supply INTEGER CHECK (supply IS NULL OR supply >= 0),
    archived INTEGER NOT NULL DEFAULT 0 CHECK (archived IN (0, 1)),
    created_at TEXT NOT NULL,
    critical INTEGER NOT NULL DEFAULT 0 CHECK (critical IN (0, 1)),
    UNIQUE (id, household_id),
    FOREIGN KEY (member_id, household_id) REFERENCES household_members(id, household_id) ON DELETE CASCADE,
    FOREIGN KEY (remind_member_id, household_id) REFERENCES household_members(id, household_id) ON DELETE SET NULL (remind_member_id)
);

CREATE TABLE kid_med_log (
    med_id TEXT NOT NULL,
    household_id TEXT NOT NULL,
    day TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('given', 'missed')),
    logged_at TEXT NOT NULL,
    PRIMARY KEY (med_id, day),
    FOREIGN KEY (med_id, household_id) REFERENCES kid_meds(id, household_id) ON DELETE CASCADE
);

CREATE TABLE kid_school_slots (
    id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL,
    member_id TEXT NOT NULL,
    weekday INTEGER NOT NULL CHECK (weekday BETWEEN 0 AND 6),
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    title TEXT NOT NULL CHECK (length(trim(title)) > 0),
    kind TEXT NOT NULL CHECK (kind IN ('lesson', 'break', 'meal', 'care')),
    note TEXT,
    FOREIGN KEY (member_id, household_id) REFERENCES household_members(id, household_id) ON DELETE CASCADE
);
CREATE INDEX kid_school_slots_by_member ON kid_school_slots(member_id, weekday, start_time);

CREATE TABLE kid_tasks (
    id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL,
    member_id TEXT NOT NULL,
    kind TEXT NOT NULL CHECK (kind IN ('homework', 'test')),
    subject TEXT,
    title TEXT NOT NULL CHECK (length(trim(title)) > 0),
    due_on TEXT NOT NULL,
    note TEXT,
    done_at TEXT,
    created_by TEXT NOT NULL CHECK (created_by IN ('parent', 'child')),
    created_at TEXT NOT NULL,
    dismissed_at TEXT,
    FOREIGN KEY (member_id, household_id) REFERENCES household_members(id, household_id) ON DELETE CASCADE
);
CREATE INDEX kid_tasks_by_member ON kid_tasks(member_id, due_on);

CREATE TABLE kid_bag_items (
    id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL,
    member_id TEXT NOT NULL,
    subject TEXT NOT NULL CHECK (length(trim(subject)) > 0),
    label TEXT NOT NULL CHECK (length(trim(label)) > 0),
    created_by TEXT NOT NULL CHECK (created_by IN ('parent', 'child')),
    created_at TEXT NOT NULL,
    UNIQUE (member_id, subject, label),
    FOREIGN KEY (member_id, household_id) REFERENCES household_members(id, household_id) ON DELETE CASCADE
);

CREATE TABLE kid_bag_ticks (
    member_id TEXT NOT NULL,
    household_id TEXT NOT NULL,
    day TEXT NOT NULL,
    key TEXT NOT NULL,
    ticked_at TEXT NOT NULL,
    PRIMARY KEY (member_id, day, key),
    FOREIGN KEY (member_id, household_id) REFERENCES household_members(id, household_id) ON DELETE CASCADE
);

CREATE TABLE kid_privacy_policy (
    household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
    section TEXT NOT NULL CHECK (section IN ('grades', 'health')),
    min_age INTEGER NOT NULL CHECK (min_age BETWEEN 0 AND 18),
    PRIMARY KEY (household_id, section)
);

CREATE TABLE kid_privacy (
    member_id TEXT NOT NULL,
    household_id TEXT NOT NULL,
    section TEXT NOT NULL CHECK (section IN ('grades', 'health')),
    private INTEGER NOT NULL DEFAULT 0 CHECK (private IN (0, 1)),
    updated_at TEXT NOT NULL,
    PRIMARY KEY (member_id, section),
    FOREIGN KEY (member_id, household_id) REFERENCES household_members(id, household_id) ON DELETE CASCADE
);

-- Kid phone (ADR-0012) -------------------------------------------------------------------------------------------

CREATE TABLE kid_phone_access (
    member_id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL,
    enabled INTEGER NOT NULL DEFAULT 0 CHECK (enabled IN (0, 1)),
    -- what the phone may show; grades and health are off until a parent turns them on (strict privacy class)
    share_timetable INTEGER NOT NULL DEFAULT 1 CHECK (share_timetable IN (0, 1)),
    share_stars INTEGER NOT NULL DEFAULT 1 CHECK (share_stars IN (0, 1)),
    share_reminders INTEGER NOT NULL DEFAULT 1 CHECK (share_reminders IN (0, 1)),
    share_grades INTEGER NOT NULL DEFAULT 0 CHECK (share_grades IN (0, 1)),
    share_health INTEGER NOT NULL DEFAULT 0 CHECK (share_health IN (0, 1)),
    updated_at TEXT NOT NULL,
    share_homework INTEGER NOT NULL DEFAULT 1 CHECK (share_homework IN (0, 1)),
    share_activities INTEGER NOT NULL DEFAULT 1 CHECK (share_activities IN (0, 1)),
    share_bag INTEGER NOT NULL DEFAULT 1 CHECK (share_bag IN (0, 1)),
    FOREIGN KEY (member_id, household_id) REFERENCES household_members(id, household_id) ON DELETE CASCADE
);

CREATE TABLE kid_phone_devices (
    id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL,
    member_id TEXT NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,       -- sha256 of the device token; the token itself lives only on the phone
    label TEXT,
    paired_at TEXT NOT NULL,
    last_seen_at TEXT,
    revoked_at TEXT,
    UNIQUE (id, household_id),
    FOREIGN KEY (member_id, household_id) REFERENCES household_members(id, household_id) ON DELETE CASCADE
);
CREATE INDEX kid_phone_devices_by_member ON kid_phone_devices(member_id);

CREATE TABLE kid_phone_handoffs (
    token_hash TEXT PRIMARY KEY,
    device_id TEXT NOT NULL,
    household_id TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    used INTEGER NOT NULL DEFAULT 0 CHECK (used IN (0, 1)),
    FOREIGN KEY (device_id, household_id) REFERENCES kid_phone_devices(id, household_id) ON DELETE CASCADE
);

CREATE TABLE kid_phone_pairings (
    id TEXT PRIMARY KEY,
    household_id TEXT NOT NULL,
    member_id TEXT NOT NULL,
    secret_hash TEXT NOT NULL UNIQUE,      -- sha256 of the QR secret
    code_salt TEXT NOT NULL,
    code_hash TEXT NOT NULL,               -- sha256(salt + 6-digit code)
    attempts INTEGER NOT NULL DEFAULT 0,
    expires_at TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'used', 'cancelled', 'locked')),
    created_at TEXT NOT NULL,
    link_hash TEXT,
    FOREIGN KEY (member_id, household_id) REFERENCES household_members(id, household_id) ON DELETE CASCADE
);
CREATE INDEX kid_phone_pairings_by_link ON kid_phone_pairings(link_hash);
CREATE INDEX kid_phone_pairings_by_member ON kid_phone_pairings(member_id, status);

-- Integrity rules that were SQLite triggers --------------------------------------------------------------------------

CREATE FUNCTION chit_household_owner_must_be_adult() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM household_members
                   WHERE id = NEW.owner_member_id AND household_id = NEW.id AND role = 'adult') THEN
        RAISE EXCEPTION 'household owner must be an adult in this household';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER household_owner_must_be_adult
    BEFORE UPDATE OF owner_member_id ON households
    FOR EACH ROW EXECUTE FUNCTION chit_household_owner_must_be_adult();

CREATE FUNCTION chit_household_owner_cannot_be_removed() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM households WHERE id = OLD.household_id AND owner_member_id = OLD.id) THEN
        RAISE EXCEPTION 'transfer household ownership before removing the owner';
    END IF;
    RETURN OLD;
END $$;
CREATE TRIGGER household_owner_cannot_be_removed
    BEFORE DELETE ON household_members
    FOR EACH ROW EXECUTE FUNCTION chit_household_owner_cannot_be_removed();

CREATE FUNCTION chit_child_adult_assignment() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM household_members
                   WHERE id = NEW.child_id AND household_id = NEW.household_id AND role = 'child')
       OR NOT EXISTS (SELECT 1 FROM household_members
                      WHERE id = NEW.adult_id AND household_id = NEW.household_id AND role = 'adult') THEN
        RAISE EXCEPTION '% assignment must link a child to an adult in the same household', TG_ARGV[0];
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER child_pickup_assignment_must_be_adult
    BEFORE INSERT ON child_pickup_adults
    FOR EACH ROW EXECUTE FUNCTION chit_child_adult_assignment('pickup');
CREATE TRIGGER child_dropoff_assignment_must_be_adult
    BEFORE INSERT ON child_dropoff_adults
    FOR EACH ROW EXECUTE FUNCTION chit_child_adult_assignment('drop-off');
