-- 1. The SQLite code breaks ties on `households` with rowid ("latest household"); Postgres uses seq instead.
ALTER TABLE households ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- 2. Fifteen tables carry household_id in Postgres but not in SQLite, so the shared query code does not supply it.
--    A BEFORE INSERT trigger copies it from the parent row. Because it is derived from the parent (never from the
--    caller), a child row can only ever belong to its parent's household; if the parent is missing or invisible
--    the value stays NULL and the NOT NULL constraint rejects the insert.
CREATE FUNCTION chit_fill_household_id() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    -- TG_ARGV: parent table, child column that points at it, parent column it points to
    derived TEXT;
BEGIN
    IF NEW.household_id IS NULL THEN
        EXECUTE format('SELECT household_id FROM %I WHERE %I = $1', TG_ARGV[0], TG_ARGV[2])
            INTO derived USING (to_jsonb(NEW) ->> TG_ARGV[1]);
        NEW.household_id := derived;
    END IF;
    RETURN NEW;
END $$;

CREATE TRIGGER fill_household_id BEFORE INSERT ON adult_settings        FOR EACH ROW EXECUTE FUNCTION chit_fill_household_id('household_members', 'member_id', 'id');
CREATE TRIGGER fill_household_id BEFORE INSERT ON child_settings        FOR EACH ROW EXECUTE FUNCTION chit_fill_household_id('household_members', 'member_id', 'id');
CREATE TRIGGER fill_household_id BEFORE INSERT ON kid_bag_ticks         FOR EACH ROW EXECUTE FUNCTION chit_fill_household_id('household_members', 'member_id', 'id');
CREATE TRIGGER fill_household_id BEFORE INSERT ON kid_privacy           FOR EACH ROW EXECUTE FUNCTION chit_fill_household_id('household_members', 'member_id', 'id');
CREATE TRIGGER fill_household_id BEFORE INSERT ON member_modules        FOR EACH ROW EXECUTE FUNCTION chit_fill_household_id('household_members', 'member_id', 'id');
CREATE TRIGGER fill_household_id BEFORE INSERT ON adult_work_days       FOR EACH ROW EXECUTE FUNCTION chit_fill_household_id('adult_settings', 'member_id', 'member_id');
CREATE TRIGGER fill_household_id BEFORE INSERT ON child_care_days       FOR EACH ROW EXECUTE FUNCTION chit_fill_household_id('child_settings', 'member_id', 'member_id');
CREATE TRIGGER fill_household_id BEFORE INSERT ON child_activities      FOR EACH ROW EXECUTE FUNCTION chit_fill_household_id('child_settings', 'member_id', 'member_id');
CREATE TRIGGER fill_household_id BEFORE INSERT ON child_activity_days   FOR EACH ROW EXECUTE FUNCTION chit_fill_household_id('child_activities', 'activity_id', 'id');
CREATE TRIGGER fill_household_id BEFORE INSERT ON chore_completions     FOR EACH ROW EXECUTE FUNCTION chit_fill_household_id('chore_series', 'series_id', 'id');
CREATE TRIGGER fill_household_id BEFORE INSERT ON kid_chore_outcomes    FOR EACH ROW EXECUTE FUNCTION chit_fill_household_id('chore_series', 'series_id', 'id');
CREATE TRIGGER fill_household_id BEFORE INSERT ON kid_star_chores       FOR EACH ROW EXECUTE FUNCTION chit_fill_household_id('chore_series', 'series_id', 'id');
CREATE TRIGGER fill_household_id BEFORE INSERT ON kid_grades            FOR EACH ROW EXECUTE FUNCTION chit_fill_household_id('kid_subjects', 'subject_id', 'id');
CREATE TRIGGER fill_household_id BEFORE INSERT ON kid_med_log           FOR EACH ROW EXECUTE FUNCTION chit_fill_household_id('kid_meds', 'med_id', 'id');
CREATE TRIGGER fill_household_id BEFORE INSERT ON kid_phone_handoffs    FOR EACH ROW EXECUTE FUNCTION chit_fill_household_id('kid_phone_devices', 'device_id', 'id');
