#!/bin/sh
# One-time local Postgres setup for development (ADR-0015). Run it yourself: psql asks for the `postgres`
# superuser password you chose when installing PostgreSQL. Creates, idempotently:
#   roles     chit_owner (owns the schema, runs migrations) and chit_app (the application; no BYPASSRLS, not an owner)
#   databases chit_dev (imported household data) and chit_test (tests)
# and writes generated passwords to .env.postgres (git-ignored, mode 600). Re-running rotates the passwords.
set -eu
cd "$(dirname "$0")/.."
PSQL="${PSQL:-/Library/PostgreSQL/17/bin/psql}"
HOST=127.0.0.1; PORT=5432
export PGGSSENCMODE=disable   # avoids a Kerberos lookup on managed Macs

OWNER_PW=$(openssl rand -hex 16)
APP_PW=$(openssl rand -hex 16)

"$PSQL" -h "$HOST" -p "$PORT" -U postgres -d postgres -v ON_ERROR_STOP=1 -v owner_pw="$OWNER_PW" -v app_pw="$APP_PW" <<'SQL'
SELECT format('CREATE ROLE chit_owner LOGIN') WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'chit_owner') \gexec
SELECT format('CREATE ROLE chit_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS') WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'chit_app') \gexec
ALTER ROLE chit_owner PASSWORD :'owner_pw';
ALTER ROLE chit_app PASSWORD :'app_pw';
SELECT format('CREATE DATABASE %I OWNER chit_owner', d) FROM (VALUES ('chit_dev'), ('chit_test')) v(d)
  WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = d) \gexec
SQL

umask 077
cat > .env.postgres <<EOF
# Local development only. Generated by scripts/pg-local-setup.sh. Never commit.
CHIT_PG_OWNER_URL=postgresql://chit_owner:${OWNER_PW}@${HOST}:${PORT}/chit_dev
CHIT_PG_APP_URL=postgresql://chit_app:${APP_PW}@${HOST}:${PORT}/chit_dev
CHIT_PG_TEST_OWNER_URL=postgresql://chit_owner:${OWNER_PW}@${HOST}:${PORT}/chit_test
CHIT_PG_TEST_APP_URL=postgresql://chit_app:${APP_PW}@${HOST}:${PORT}/chit_test
EOF
echo "Done. Roles chit_owner / chit_app and databases chit_dev / chit_test exist; credentials are in .env.postgres"
